// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorVendas.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonitorVendas.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730175018_ReportExports")]
    partial class ReportExports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonitorVendas.Api.Features.Ai.AiUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualBrl")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedBrl")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("WindowStart", "Status");

                    b.ToTable("ai_usages", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Ai.Analysis.ConversationAiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AskedForSale")
                        .HasColumnType("boolean");

                    b.Property<string>("ConductAlert")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostBrl")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IgnoredBuyingSignal")
                        .HasColumnType("boolean");

                    b.Property<string>("Interest")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LossReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Objections")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecontactReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("ShouldRecontact")
                        .HasColumnType("boolean");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double>("StatusConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("StatusEvidence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SuggestedMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.ToTable("conversation_ai_analyses", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Contacts.ContactShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SenderNumberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalContacts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SenderNumberId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("contact_shares", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Contacts.ContactShareMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContactShareId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("WaMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("WaMessageId");

                    b.HasIndex("ContactShareId", "Sequence")
                        .IsUnique();

                    b.ToTable("contact_share_messages", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PushName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RemoteJid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RemoteJid")
                        .IsUnique();

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StartedByContact")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WhatsappNumberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("WhatsappNumberId", "StartedAt");

                    b.HasIndex("WhatsappNumberId", "ContactId", "LastMessageAt");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.ConversationLabel", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LabelId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LabelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConversationId", "LabelId");

                    b.HasIndex("AppliedAt");

                    b.ToTable("conversation_labels", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.ConversationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LabelId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeTypeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("OutcomeTypeCode", "MarkedAt");

                    b.ToTable("conversation_outcomes", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WaMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WhatsappNumberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ConversationId", "Timestamp");

                    b.HasIndex("WhatsappNumberId", "WaMessageId")
                        .IsUnique();

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.WhatsappLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LabelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceName", "LabelId")
                        .IsUnique();

                    b.ToTable("whatsapp_labels", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Metrics.DailyNumberMetrics", b =>
                {
                    b.Property<Guid>("WhatsappNumberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("BanCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConversationsAnswered")
                        .HasColumnType("integer");

                    b.Property<int>("ConversationsStarted")
                        .HasColumnType("integer");

                    b.Property<double>("DowntimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("EffectiveBusinessHours")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<int[]>("FirstResponseHistogram")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("LastOutboundMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessagesReceived")
                        .HasColumnType("integer");

                    b.Property<int>("MessagesSent")
                        .HasColumnType("integer");

                    b.Property<int>("OutboundConversationsEngaged")
                        .HasColumnType("integer");

                    b.Property<int>("OutboundConversationsStarted")
                        .HasColumnType("integer");

                    b.Property<int>("OutboundRead")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseCount")
                        .HasColumnType("integer");

                    b.Property<double?>("ResponseMinutesMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("ResponseMinutesMin")
                        .HasColumnType("double precision");

                    b.Property<double>("ResponseMinutesSum")
                        .HasColumnType("double precision");

                    b.Property<int>("SilenceGaps")
                        .HasColumnType("integer");

                    b.Property<int>("SilenceGapsFollowedUp")
                        .HasColumnType("integer");

                    b.HasKey("WhatsappNumberId", "Day");

                    b.HasIndex("Day");

                    b.ToTable("daily_number_metrics", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Metrics.DailyNumberOutcomeMetrics", b =>
                {
                    b.Property<Guid>("WhatsappNumberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("OutcomeTypeCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("TimeToCloseCount")
                        .HasColumnType("integer");

                    b.Property<double>("TimeToCloseHoursSum")
                        .HasColumnType("double precision");

                    b.HasKey("WhatsappNumberId", "Day", "OutcomeTypeCode");

                    b.HasIndex("Day", "OutcomeTypeCode");

                    b.ToTable("daily_number_outcome_metrics", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Metrics.DirtyMetricsDay", b =>
                {
                    b.Property<Guid>("WhatsappNumberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WhatsappNumberId", "Day");

                    b.ToTable("dirty_metrics_days", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Metrics.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Numbers.NumberStatusEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("StatusReason")
                        .HasColumnType("integer");

                    b.Property<Guid>("WhatsappNumberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WhatsappNumberId", "OccurredAt");

                    b.ToTable("number_status_events", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Numbers.WhatsappNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceName")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("whatsapp_numbers", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Outcomes.ConversationOutcomeType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.ToTable("conversation_outcome_types", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "sale",
                            Active = true,
                            Name = "Vendas",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "lost",
                            Active = true,
                            Name = "Clientes perdidos",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Outcomes.OutcomeLabelTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OutcomeTypeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedKey")
                        .IsUnique();

                    b.HasIndex("OutcomeTypeCode");

                    b.ToTable("outcome_label_terms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a1e0001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            NormalizedKey = "venda",
                            OutcomeTypeCode = "sale",
                            Term = "venda"
                        },
                        new
                        {
                            Id = new Guid("1a1e0001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            NormalizedKey = "perdido",
                            OutcomeTypeCode = "lost",
                            Term = "perdido"
                        });
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.ReportExport.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnalyzedConversations")
                        .HasColumnType("integer");

                    b.Property<int>("CachedConversations")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CostBrl")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkippedConversations")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalConversations")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("report_exports", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Sellers.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Webhooks.WebhookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasFilter("\"DedupeKey\" IS NOT NULL");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("webhook_events", (string)null);
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Ai.Analysis.ConversationAiAnalysis", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Contacts.ContactShare", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Numbers.WhatsappNumber", null)
                        .WithMany()
                        .HasForeignKey("SenderNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Contacts.ContactShareMessage", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Contacts.ContactShare", null)
                        .WithMany()
                        .HasForeignKey("ContactShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.Conversation", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Conversations.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitorVendas.Api.Features.Numbers.WhatsappNumber", null)
                        .WithMany()
                        .HasForeignKey("WhatsappNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.ConversationLabel", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.ConversationOutcome", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Conversations.Message", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Metrics.DailyNumberMetrics", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Numbers.WhatsappNumber", null)
                        .WithMany()
                        .HasForeignKey("WhatsappNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Metrics.DailyNumberOutcomeMetrics", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Numbers.WhatsappNumber", null)
                        .WithMany()
                        .HasForeignKey("WhatsappNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Numbers.NumberStatusEvent", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Numbers.WhatsappNumber", null)
                        .WithMany()
                        .HasForeignKey("WhatsappNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Numbers.WhatsappNumber", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Sellers.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorVendas.Api.Features.Outcomes.OutcomeLabelTerm", b =>
                {
                    b.HasOne("MonitorVendas.Api.Features.Outcomes.ConversationOutcomeType", null)
                        .WithMany()
                        .HasForeignKey("OutcomeTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
